[portfolio]
ticker1 = "ENGI.PA"
ticker2= "VIE.PA"
ticker3 = "^FCHI"

[analyse]
ticker1 = "ENGI.PA"
ticker2= "VIE.PA"

[initialisation]
field_to_keep = "Close"
begin_date = "2022-01-01"
end_date = "2024-12-31"

[chart]
colorCAC40 = "blue"
colorCompany1 = "red"
colorCompany2 = "green"
title= "Cours du CAC40 vs "

