[portfolio]
ticker1 = "ENGI.PA"
ticker2= "VIE.PA"
ticker3 = "^FCHI"

[initialisation]
field_to_keep = "Close"
begin_date = "2020-01-01"
end_date = "2024-12-31"

[chart]
colorCAC40 = "blue"
colorCompany1 = "red"
colorCompany2 = "green"
column1 = "ENGI.PA"
column2 = "VIE.PA"
column3 = "^FCHI"
label1 = "Engie"
label2 = "Veolia"
label3 = "CAC40"
legend_loc1 = "upper left"
legend_loc2 = "upper right"
rotation = 90

[chart_ebitda]
x = "Date"
y = "EBITDA"
marker = "o"
label1 = "Year"
label2 = "EBITDA"
title = "Evolution de l'EBITDA"

[net_debt]
column1 = "Date"
column2 = "Total Debt"
column3 = "Cash And Cash Equivalents"


